import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* Navbar */}
        <nav
          style={{ padding: "10px", backgroundColor: "#333", color: "#fff" }}
        >
          <Link href="/" style={{ marginRight: "20px", color: "#fff" }}>
            Home
          </Link>
          <Link href="/Map" style={{ marginRight: "20px", color: "#fff" }}>
            Map
          </Link>
        </nav>

        {/* Sayfa içeriği */}
        <main>{children}</main>
      </body>
    </html>
  );
}
